language: python
python:
    "2.7"
addons:
    firefox: "53.0"
before_install:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.16.1-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver
install:
    make init

before_script:
    make runServer
    
script:
    make test

